import { Inter } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {

  return (
    <div >
      <SessionProvider>
        <div>
          <Navbar />
          <div>{children}</div>
          <Footer />
        </div>
      </SessionProvider>
    </div>
  );
}
