import React from 'react';
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import Sidebar from '@/components/AdminSiderBar';
import AdminNavbar from '@/components/AdminNavbar';
import { auth } from '@/app/auth';
import { redirect } from 'next/dist/server/api-utils';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminDashboard({ children }) {

    return (
        <div>
            <SessionProvider>
                <div className={inter.className}>
                    <AdminNavbar />
                    <div className='flex' >
                        <div className="w-[20%]">
                            <Sidebar />
                        </div>
                        <div className="w-[80%]">{children}</div>
                    </div>
                </div>
            </SessionProvider>
        </div>

    );
}

