import React from 'react';
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import Sidebar from '@/components/AdminSiderBar';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <SessionProvider>
            <div className={inter.className}>
                <div >
                    <div className="w-[20%]">
                    <Sidebar />
                    </div>
                    <div className="w-[80%]">{children}</div>
                </div>
            </div>
        </SessionProvider>
    );
}
